// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsX_uPsEkLgRj0GgAhVizarGTevXDCDSs',
    appId: '1:44590268831:web:551d7d62a1b6d2eb16bdaa',
    messagingSenderId: '44590268831',
    projectId: 'lechonk-fc8a5',
    authDomain: 'lechonk-fc8a5.firebaseapp.com',
    storageBucket: 'lechonk-fc8a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSIsx6oMqJ1sVse8l_zKZnoynVg9qHjfA',
    appId: '1:44590268831:android:079b698568f0f34b16bdaa',
    messagingSenderId: '44590268831',
    projectId: 'lechonk-fc8a5',
    storageBucket: 'lechonk-fc8a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz64cSC0yuiea6LHjXRzSlAF33uC9rars',
    appId: '1:44590268831:ios:0ae1afe5f9f998d516bdaa',
    messagingSenderId: '44590268831',
    projectId: 'lechonk-fc8a5',
    storageBucket: 'lechonk-fc8a5.appspot.com',
    iosClientId: '44590268831-ep1nottv057p37hcpg40sdoqs4ev9jbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lechonk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz64cSC0yuiea6LHjXRzSlAF33uC9rars',
    appId: '1:44590268831:ios:0ae1afe5f9f998d516bdaa',
    messagingSenderId: '44590268831',
    projectId: 'lechonk-fc8a5',
    storageBucket: 'lechonk-fc8a5.appspot.com',
    iosClientId: '44590268831-ep1nottv057p37hcpg40sdoqs4ev9jbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lechonk',
  );
}
